### ISSUE TITLE
Add missing compile instruction documents

### ISSUE THREAD

**Issue by yeroca** [pleccer/Pleccer#4]
**Is your feature request related to a problem? Please describe.**
Compile doc links in the README.md point to non-existent docs

**Describe the solution you'd like**
Usable compile docs.

**Describe how it would work**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pleccer** [comment]
Updated the links.
GLHF, may the source be willing to you.
